et ddp_sampler drop_last True
lifeiteng/vall-e pull request #131
Opened 2023-06-06 13:51 UTC by jiazj-jiazj

1，Set **DynamicBucketingSampler drop_last=True** to avoid different number of batches on multiple gpus. It is a bug in lhotse. The pr is trying to fix the problem.[Fix samplers dropping cuts when world_size > 1 ](https://github.com/lhotse-speech/lhotse/pull/695)
2, No need to use "torch.distributed.barrier()“.

2023-06-06 14:36 UTC, chenjiasheng approved these changes
@jiazj-jiazj 
Distributed training is a pain for us.
lifeiteng himself has only one GPU, and he is busy these days. 
It is also difficult for me, as I use my private trainer.py and I am in company's private network.
So the PR is very valuable to us.

setting drop_last=True sounds reasonable to me.
If you can ensure the code is well tested, we are glad to merge the PR.
Could you please test it on both single-rank and multi-rank?

2023-06-07 01:14 UTC, lifeiteng requested changes

2023-06-07 01:14 UTC, lifeiteng commented on valle/data/datamodule.py
> +                drop_last=True,
change default value of `--drop-last` to True

2023-06-07 01:14 UTC, lifeiteng commented on valle/data/datamodule.py
> +            drop_last=True,
self.args.drop_last

2023-06-07 01:14 UTC, lifeiteng commented on valle/data/datamodule.py
> +            drop_last=True,
self.args.drop_last

2023-06-07 01:30 UTC, lifeiteng requested changes

2023-06-07 01:30 UTC, lifeiteng commented on valle/bin/trainer.py
> +    if world_size > 1:
@jiazj-jiazj 
```
if params.visualize:
 model. DDP 也要修改
```

2023-06-07 01:30 UTC, lifeiteng commented on valle/data/datamodule.py
> +                drop_last=True,
加上必要的注释说明（world_size > 1 必须 == True)

2023-06-07 01:37 UTC, chenjiasheng commented on valle/data/datamodule.py
> +            drop_last=True,
这个PR的意义，就是multi-rank情况下强制drop_last，以免之前遇到的那些麻烦。
所以这里就该直接drop_last=True；
如果用self.args.drop_last，不知情的使用者又会犯迷糊了。
我们可以在文档中注明，dataloader是强制drop_last的。
牺牲一点自由度，避免更多的麻烦。

2023-06-07 14:20 UTC, lifeiteng commented on valle/data/datamodule.py
> +            drop_last=True,
可以在 world_size > 1 强制 args.drop_last = True；我当时想还是保留 GPU=1 时的完整

2023-06-08 12:53 UTC, merged

2023-06-11 13:23 UTC, RuntimeRacer commented
FYI I just tested this on my 6x3090 Machine and it works like a charm. Good Job 👍