For chinese aishell1 egs
lifeiteng/vall-e pull request #68
Opened 2023-03-28 04:04 UTC by zhaomingwork

add aishell1 egs. you should set NUM_TEXT_TOKENS = 1280 in valle.py. Attached is the generated wav demo. 
[infer_demo.zip](https://github.com/lifeiteng/vall-e/files/11085143/infer_demo.zip)

2023-03-28 13:32 UTC, lifeiteng requested changes

2023-03-28 13:32 UTC, lifeiteng commented on egs/aishell1/README.md
> +    --text-prompts "KNOT one point one five miles per hour." \
大家好非常高兴能认识大家

2023-03-28 13:32 UTC, lifeiteng commented on egs/aishell1/README.md
> +    --audio-prompts ./prompts/8463_294825_000043_000000.wav \
`./prompts/ch_24k.wav`

2023-03-28 13:32 UTC, lifeiteng commented on egs/aishell1/run.sh
> +    lhotse download aishell   $dl_dir
format

2023-03-28 13:32 UTC, lifeiteng commented on egs/aishell1/run.sh
> +      # train
format

we should add `precommit for shell scripts`

2023-03-28 13:32 UTC, lifeiteng commented on egs/aishell1/run.sh
> +    --num-epochs ${num_epochs} --start-epoch 1 --start-batch 0 --world-size 7\
add hparam `--world-size` for run.sh

2023-03-28 13:32 UTC, lifeiteng commented on egs/aishell1/shared/parse_options.sh
> +
`ln -s ../libritts/shared/`

2023-03-28 13:32 UTC, lifeiteng commented on egs/aishell1/README.md
> +pip install librosa==0.8.1
+pypinyin

2023-03-28 13:57 UTC, lifeiteng commented on egs/aishell1/run.sh
> +#      You can download aishell from https://www.openslr.org/60/
/33

2023-03-29 01:35 UTC, zhaomingwork commented on egs/aishell1/run.sh
> +#      You can download aishell from https://www.openslr.org/60/
OK. Commited all to one.

2023-03-31 03:04 UTC, lifeiteng approved these changes

2023-03-31 03:04 UTC, lifeiteng commented on valle/tests/data/pypinyin_test.py
> +    unittest.main()
fine

2023-03-31 08:11 UTC, sanqianyuejia commented
> add aishell1 egs. you should set NUM_TEXT_TOKENS = 1280 in valle.py. Attached is the generated wav demo. [infer_demo.zip](https://github.com/lifeiteng/vall-e/files/11085143/infer_demo.zip)

Errors will occur due to the existence of english words in the corpus text.

2023-03-31 08:50 UTC, zhaomingwork commented
> > add aishell1 egs. you should set NUM_TEXT_TOKENS = 1280 in valle.py. Attached is the generated wav demo. [infer_demo.zip](https://github.com/lifeiteng/vall-e/files/11085143/infer_demo.zip)
> 
> Errors will occur due to the existence of english words in the corpus text.

Had fixed a bug for SPACE problem, you can try again.  Or you can tell me the detail about the Error. Thx!

2023-04-12 07:24 UTC, merged